remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Resources from COS Colloquium on Charting a Path for Research Integrity]
description: This site will be updated with resources and links discussed at the Center for Open Science's December 12th Colloquium <em>At a Crossroads: Charting a Path for Research Integrity</em>
